// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCojfHQUxn-fo3OiJjOky1CupPyojPRI24',
    appId: '1:1072868256610:web:2c961823324d9eb08d9a3b',
    messagingSenderId: '1072868256610',
    projectId: 'flutter-ecommerce-80ed9',
    authDomain: 'flutter-ecommerce-80ed9.firebaseapp.com',
    storageBucket: 'flutter-ecommerce-80ed9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvD1InF5c1dtcFLHanp8EVDWC2EkPzo2I',
    appId: '1:1072868256610:android:c6a41e9de9a3c32b8d9a3b',
    messagingSenderId: '1072868256610',
    projectId: 'flutter-ecommerce-80ed9',
    storageBucket: 'flutter-ecommerce-80ed9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIeqeZU8tb3kWLeqFF2NKE8fUwPIWu5vc',
    appId: '1:1072868256610:ios:b2ce5c1b4b670a928d9a3b',
    messagingSenderId: '1072868256610',
    projectId: 'flutter-ecommerce-80ed9',
    storageBucket: 'flutter-ecommerce-80ed9.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIeqeZU8tb3kWLeqFF2NKE8fUwPIWu5vc',
    appId: '1:1072868256610:ios:b2ce5c1b4b670a928d9a3b',
    messagingSenderId: '1072868256610',
    projectId: 'flutter-ecommerce-80ed9',
    storageBucket: 'flutter-ecommerce-80ed9.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCojfHQUxn-fo3OiJjOky1CupPyojPRI24',
    appId: '1:1072868256610:web:88da2dc9c4558f5f8d9a3b',
    messagingSenderId: '1072868256610',
    projectId: 'flutter-ecommerce-80ed9',
    authDomain: 'flutter-ecommerce-80ed9.firebaseapp.com',
    storageBucket: 'flutter-ecommerce-80ed9.firebasestorage.app',
  );
}
